In [17]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.svm import LinearSVC
from sklearn.datasets import load_digits

In [19]:
digit = datasets.load_digits()

In [21]:
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [22]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [23]:
digit.data.shape, digit.target.shape

((1797, 64), (1797,))

In [24]:
Atribut_Training, Atribut_Testing, Kelas_Training, Kelas_Testing = train_test_split(digit.data,
                                                                                    digit.target,
                                                                                    test_size=0.4,
                                                                                    random_state=0)

In [25]:
Atribut_Training.shape, Atribut_Testing.shape

((1078, 64), (719, 64))

In [26]:
Kelas_Training.shape, Atribut_Testing.shape

((1078,), (719, 64))

In [27]:
modelSVM = LinearSVC()
modelSVM.fit(Atribut_Training,Kelas_Training)

C:\Users\yoiji\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC()

In [28]:
modelSVM.predict(Atribut_Testing)

array([2, 8, 2, 6, 6, 7, 1, 9, 3, 5, 2, 8, 6, 6, 6, 6, 1, 0, 5, 8, 8, 7,
       8, 4, 7, 5, 4, 9, 2, 9, 4, 7, 6, 8, 9, 4, 3, 8, 0, 1, 8, 6, 7, 7,
       1, 0, 7, 6, 2, 1, 9, 6, 7, 9, 0, 0, 5, 1, 6, 3, 0, 2, 3, 4, 1, 9,
       2, 6, 9, 1, 8, 3, 5, 1, 2, 1, 2, 2, 9, 7, 1, 3, 6, 0, 5, 5, 7, 5,
       1, 2, 9, 9, 3, 1, 4, 7, 4, 8, 5, 9, 5, 5, 2, 6, 9, 0, 7, 1, 4, 4,
       3, 4, 8, 9, 7, 8, 8, 2, 4, 5, 2, 5, 8, 4, 1, 7, 0, 6, 1, 5, 5, 9,
       9, 5, 9, 9, 5, 7, 5, 6, 2, 8, 6, 9, 6, 1, 5, 1, 5, 9, 9, 1, 5, 3,
       6, 1, 8, 9, 8, 7, 6, 7, 6, 5, 6, 0, 8, 8, 9, 3, 6, 1, 0, 4, 1, 6,
       3, 8, 6, 7, 4, 1, 6, 3, 0, 3, 3, 3, 0, 7, 7, 5, 7, 8, 0, 7, 1, 9,
       6, 4, 5, 0, 1, 4, 6, 4, 3, 3, 0, 9, 5, 3, 2, 1, 4, 2, 1, 6, 9, 9,
       2, 4, 9, 3, 7, 6, 2, 3, 3, 1, 6, 9, 3, 6, 3, 2, 2, 0, 7, 6, 1, 1,
       9, 7, 2, 7, 8, 5, 5, 7, 5, 3, 3, 7, 2, 7, 5, 5, 7, 0, 9, 1, 6, 1,
       9, 7, 4, 3, 8, 0, 3, 6, 4, 6, 3, 2, 6, 8, 8, 8, 4, 6, 7, 5, 2, 4,
       5, 3, 2, 4, 6, 9, 4, 5, 4, 3, 4, 6, 2, 9, 0,

In [29]:
modelSVM.score(Atribut_Testing,Kelas_Testing)

0.9290681502086231

# CROS VALIDATION #

In [31]:
from sklearn.model_selection import cross_val_score

In [32]:
akurasi_cross_val_score = cross_val_score(modelSVM, digit.data, digit.target, cv=10)

C:\Users\yoiji\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yoiji\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yoiji\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yoiji\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
C:\Users\yoiji\anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations

In [34]:
akurasi_cross_val_score

array([0.9       , 0.93333333, 0.86111111, 0.86111111, 0.91666667,
       0.96111111, 0.97222222, 0.94972067, 0.84916201, 0.91620112])

In [36]:
ratarata_akurasi = akurasi_cross_val_score.mean()
ratarata_akurasi

0.9120639354438238